version: "1.0"
services:
  - name: web
    type: static
    build:
      command: cd client && npm install && npm run build
      outputDir: client/dist
    routes:
      - path: /
        type: rewrite
        target: /index.html
